jah2488/elm-companies

README.md
=> Added imby.bio to the list

README.md
=> Add Hearken

README.md
- [ x ] Company name
- [ x ] Company description
- [ x ] GitHub link
- [ x ] Sorted alphabetically
- [ x ] Lines wrapped at 80 chars
=> Add Spottt

README.md
=> Add wonktonk

README.md
=> Add new company - Tallink

README.md
=> add new company - CBANC

README.md
=> Add Bendyworks

README.md
- [x ] Company name
- [x ] Company description
- [x ] GitHub link
- [x ] Sorted alphabetically
- [x ] Lines wrapped at 80 chars
=> Added PinMeTo

README.md
=> Add DailyDrip

README.md
=> Added RexPad.

README.md
The team at carwow love and use Elm daily.
=> Add carwow

README.md
=> Added SoPost

README.md
- [x ] Company name
- [x ] Company description
- [x ] Company location
- [x ] GitHub link
- [ x] Sorted alphabetically
- [ x] Lines wrapped at 80 chars
=> Add KOVnet Netherlands

README.md
=> Add thoughtbot

README.md
=> Add iZettle

README.md
=> Added Roompact

README.md
=> Add Nomalab

README.md
=> Add Wejoinin

README.md
=> add Illuminate

README.md
=> Add CalculoJuridico from Brazil

README.md
We are a small startup developing a mobile app (IOS + Android) with React Native and Elm. One codebase to rule 'em all.
- Knipster
- Knipster is a Live Fantasy Football application
- Malta
- no Github yet, sorry :-(
- "Gaming" between "FinTech" and "LawTech"
- 80 is my default wrapping 👍
=> Add Knipster

README.md
Level is an Elm SPA, all source available on GitHub.
=> Level ❤️Elm

README.md
=> Add jambit

README.md
=> Add Culture Amp to Elm company list

README.md
=> Remove Knipster

README.md
=> Add Rakuten (e-commerce)

README.md
=> Add IBM's Decision Composer

README.md
- [ x] Company name
- [x ] Company description
- [ x] Company location
- [x ] GitHub link
- [ x] Sorted alphabetically
- [ x] Lines wrapped at 80 chars
=> Add Stowga

README.md
=> Add HubTran

README.md
=> Add Zeit.io - WIP

README.md
=> Add Coya and reordering Fintech

README.md
=> add Watermark

README.md
=> Add Basiq.

README.md
@jah2488 as determined in https://github.com/jah2488/elm-companies/issues/36#issuecomment-563499719 Microsft has been using Elm in Production since 2016 🎉 
This Pull Request adds new section "Software" (unless someone has a better suggestion).
Review: https://github.com/jah2488/elm-companies/blob/da60a3ab5e2cf685ea16c5c97fd46b0ea4f33cfc/README.md#software
=> Add Microsoft to list 

README.md
=> Add Webbhuset to list of Consulting firms fixes issue #50

README.md
We're an edtech company based in Chicago and San Francisco and have been happily using Elm for two years! Our team also founded the [Elm in the Spring conference](https://elminthespring.org) 😄
=> Add eSpark Learning

README.md
=> Add FörsäkringsGirot to the list

README.md
=> add diesdas.digital

README.md
=> Add Vy to the list

README.md
=> Add Bekk to the list

README.md
Emirates recently posted an Elm job offering in the Slack #jobs, so they must be using Elm somewhere.
=> Add Emirates to the list

README.md
=> Add Frende Forsikring to the list

README.md
=> Add Azara to the list

README.md
=> Add GlobalWebIndex to the list

README.md
=> Added Acko.com

README.md
=> Add Butternut Box to README.md

README.md
=> Add VisuWell

README.md
=> Added Click Travel

README.md
- [✅ ] Company name
- [✅] Company description
- [✅ ] Company location
- [✅ ] GitHub link
- [✅ ] Sorted alphabetically
- [✅ ] Lines wrapped at 80 chars
=> Adding Drip

README.md
=> Add Gingko

README.md
=> Virtual airwaves patch 1

README.md
A bit of context: NLX is a visual chatbot editor that currently runs 66k lines of Elm in production and maintains the [elm-arborist](https://package.elm-lang.org/packages/peterszerzo/elm-arborist/latest/) package. Here is a screenshot of the editor:
=> Add nlx.ai

README.md
=> Add Zalora

README.md
Insurello is missing from the list.
Add Insurello to the list.
Contribution checklist:
=> Add Insurello to list

README.md
=> Add Gripeless to list

README.md
=> Add Symbaloo

README.md
=> Add Scrive to the LawTech list

README.md
As it turns out we do not love Elm ☹️
=> Remove Butternut Box

README.md
Hi! We are treefin GmbH from lovely Munich, Germany. We enjoy using elm a lot in the front-end – and frequently looking for enthusiastic fellows joining our ranks. It would be a pleasure to add treefin to fintech companies using elm. 👌 👍
=> Add treefin to fintech companies (#1)

README.md
=> Add Pacific Health Dynamics

README.md
Hi everyone -- happy to be sharing our work. Let us know if you have any questions
=> Fission uses elm

README.md
=> Add Cachix

README.md
Hello! I am adding my company. Our frontend is 50% Elm right now, and we are on a mission to make it 100%.
=> Add MackeyRMS

README.md
=> Add Snapview

README.md
=> Add BEC and Simple IoT references

README.md
=> Add PINATA

README.md
=> Add Bellroy

README.md
=> Add BravoTran

README.md
=> Add Corvus Insurance to Insurance (InsurTech)  section

README.md
=> Add Prima Assicurazioni

README.md
=> Add Unison

README.md
=> Add Brilliant.org

README.md
=> Add Ava Security

README.md
=> Add Smallbrooks

README.md
=> Add Foxhound Systems

README.md
=> Add Featurespace

README.md
=> Add BPS as Elm company

README.md
Ava Security has changed its name to next DLP, and the frontend team structure has changed
=> Update Next DLP company name and description

README.md
=> Add Caribou

README.md
=> Remove dead websites

README.md
=> Add Airsequel

README.md
=> Add swiftcom

README.md
=> Add MyMeds&Me

README.md
=> elm weekly postings

README.md
=> Add Holmusk

README.md
Updates Pacific Health Dynamics after their acquisition in 2020, and the growth of their Elm codebase.
=> Rename PHD to HAMBS

README.md
=> Add Marvelsoft

README.md
=> Add Uncover

README.md
=> Add Timeline

README.md
=> Add Azimutt.app
